name: Limpeza diária da compilação

on:
  schedule:
    - cron: '0 3 * * *'  # 03:00 UTC = 04:00 Portugal
  workflow_dispatch:

jobs:
  limpar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Remover ficheiros antigos e fazer commit
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'

          git rm -f compilacao.xml compilacao.xml.gz || true

          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Limpeza diária automática dos ficheiros de compilação"
            git push
          else
            echo "Nada para limpar, repositório já está limpo."
          fi
